### ISSUE TITLE
[BUG]: Importing individual modules doesn't work using documented instructions

### ISSUE THREAD

**Issue by berengamble** [shinokada/svelte-google-materialdesign-icons#2]
### Description of the bug

Firstly, thank you for providing this very useful module 🙏 
### The problem
I wasn't able to import using the instructions in README.md - which are:
```
<script>
  import Hiking from 'svelte-google-materialdesign-icons/Hiking.svelte';
</script>

<Hiking />
```
This results in an error like this:
>Cannot find module 'svelte-google-materialdesign-icons/Star_outline.svelte' or its corresponding type declarations

***
### Workaround
The only way I could make it work was to import like this:

```
  import Hiking from 'svelte-google-materialdesign-icons/dist/Hiking.svelte';
```

### Steps To Reproduce

Try to import an individual Icon using a default import as per the docs. Such as:

```import Hiking from 'svelte-google-materialdesign-icons/Hiking.svelte';```

**Comment by shinokada** [comment]
I can't reproduce it.

https://svelte.dev/repl/e95adbb415a340dcaf1cefa19bb97a9d?version=4.2.8

**Comment by berengamble** [comment]
Oh, sorry! I just realised the import actually works, but I get an error in my IDE. I'll try to troubleshoot that. Thanks for the fast response.

<img width="580" alt="image" src="https://github.com/shinokada/svelte-google-materialdesign-icons/assets/413203/ceb092b9-22ec-4470-b129-4756cd0aac06">

**Comment by shinokada** [comment]
Try restart your IDE without your code.

**Comment by berengamble** [comment]
I tried that. As soon as I remove the code in app.d.ts, I get red lines under all of my default imports from this module. Must be something on my side. Thanks :)

**Comment by Tichss** [comment]
maybe a little late, but the problem can be solved in 2 ways:
- add the following line to your `tsconfig.json`:
```json
{
    "compilerOptions": {
        "moduleResolution": "Bundler"
    },
}
```
- OR ask [shinokada](https://github.com/shinokada) to modify `package.json` based on the following eg.:

```json
"exports": {
    "./A10K.svelte": {
      "types": "./dist/A10K.svelte.d.ts",
      "svelte": "./dist/A10K.svelte"
    },
},
"typesVersions": {
  ">4.0": {
    "A10K.svelte": ["./dist/A10K.svelte.d.ts"]
  }
}
```

ref: https://kit.svelte.dev/docs/packaging#typescript
