### ISSUE TITLE
[BUG]:  Icon component dont emmit events.

### ISSUE THREAD

**Issue by Tichss** [shinokada/svelte-google-materialdesign-icons#3]
### Description of the bug

Icon component dont emmit events.

```svelte
<Icon
    icon={Add_to_photos}
    on:click={() => console.log('asd')}
/>

```

### Steps To Reproduce

-

### Additional Information

-

**Comment by shinokada** [comment]
I just added event forwarding to v0.8.3.
Please update and let me know.

**Comment by Tichss** [comment]
Its working, sorry for late!
