### ISSUE TITLE
{@html} tag is broken during hydration so DONT USE IT! issue: https://github.com/sveltejs/svelte/issues/8213

### ISSUE THREAD

**Issue by Tichss** [shinokada/svelte-google-materialdesign-icons#6]
### Describe the bug

Dynamic icons (like menu etc...) dont update after hydration coz of `{@html}` tag.
Official svelte issue: https://github.com/sveltejs/svelte/issues/8213

so instead of this: 

```svelte
<svg>
  {@html svgpath}
</svg>
```

do something like this:

```svelte
<svg>
  {#if variation == 'outlined'}
    <path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6-1.41-1.41z" />
  {:else if variation == 'filled'}
    <path d="M16.59 8.59 12 13.17 7.41 8.59 6 10l6 6 6-6z" />
    {...}
  {/if}
</svg>
```

### Reproduction

examples in official issue...: https://github.com/sveltejs/svelte/issues/8213

### Version and System Info

```shell
doesnt matter its coz of svelte.
```

**Comment by shinokada** [comment]
Please try the latest (v1.0.4) and let me know

**Comment by Tichss** [comment]
Yeah the original problem is solved by this, but your script failed in `two-tone` version of every svelte file:

```svelte
{:else if variation === 'two-tone'}
    replace_svg_two <!-- No path tag!!! -->
{/if}
```

Please check it!

**Comment by shinokada** [comment]
Thanks. Please check the latest. (v1.0.5)

**Comment by Tichss** [comment]
Great, looks like all fine! Thank you!
