### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by subpublic** [shinokada/svelte-google-materialdesign-icons#7]
### Describe the bug

There are a bunch of new google icons missing, would be lovely if you could add them.

### Reproduction

Like Trophy
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:trophy:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=trophy&icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368

`import Trophy from 'svelte-google-materialdesign-icons/Trophy.svelte';`

### Version and System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 97.00 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.5
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.24 
    svelte: ^4.0.5 => 4.2.19 
    svelte-google-materialdesign-icons: ^1.0.5 => 1.0.5 
    vite: ^5.0.0 => 5.4.2
```

**Comment by shinokada** [comment]
I'm sorry that the original svg source are from https://github.com/marella/material-design-icons/tree/main/svg.

**Comment by subpublic** [comment]
Ah, maybe a hassle, but possible to switch to the newer lib?
https://github.com/google/material-design-icons/tree/master/symbols/web

**Comment by shinokada** [comment]
Thank you for the link. The problem is that there are too many files. When I publish an npm package, more than 4000 files fails to process it.
